### ISSUE TITLE
Impossible de se connecter au serveur

### ISSUE THREAD

**Issue by GitHubMe78** [the8tre/somfy-protexial#48]
Bonjour,
Lors de la configuration initiale après téléchargement sur Hacs, je rentre l'adresse de l'alarme ie 192.168.4.220 ou http://192.168.4.220 mais j'obtiens le message d'erreur :  Impossible de joindre le serveur.
L'interface fonctionne pourtant parfaitement à cette adresse.
Que dois-je faire ?
Cordialement

**Comment by the8tre** [comment]
Salut,
Je viens de publier une version expérimentale pour le support des centrales Somfy exposant une API plus ancienne.
Active le téléchargement des versions beta dans HACS: https://hacs.xyz/docs/faq/beta
Et installe la `1.1.0-beta.1`
Je doute que cela fonctionne dès le premier jet mais n'hésite pas à me faire des retours.
Merci

**Comment by the8tre** [comment]
il y a également un file de discussion à propos de cette intégration sur le forum HACF: https://forum.hacf.fr/t/integration-custom-centrale-somfy-protexial

**Comment by the8tre** [comment]
Résolu par la release https://github.com/the8tre/somfy-protexial/releases/tag/1.1.0
