### ISSUE TITLE
Problème avec la version 2024.6.0

### ISSUE THREAD

**Issue by phik1969** [the8tre/somfy-protexial#57]
Bonjour

La mise en service de l'alarme ne fonctionne plus avec la nouvelle version du core 2024.6.0.

J'ai fait un retour arrière sur la version 2024.5.5 --> pas de problème.

Cordialement

**Comment by the8tre** [comment]
Merci du retour, je vais regarder

**Comment by phik1969** [comment]
voici le message d'erreur

Échec de l'appel du service alarm_control_panel/alarm_arm_away. Validation error: Arming requires a code but none was given for alarm_control_panel.alarme

**Comment by Yoshi939** [comment]
Bonjour,

Des news sur une éventuelle maj sur les nouvelles versions?

En vous remerciant ;)

**Comment by Yoshi939** [comment]
Bon apparemment, il faut rajouter un code dans la configuration. Avant je pouvais activer/désactiver l'alarme, sans rentrer de code. J'ai l'impression que maintenant c'est obligatoire. En tout cas, ça refonctionne chez moi ;)

**Comment by the8tre** [comment]
Désolé pour le manque de réactivé.
Je devrais avoir plus de temps à partir de la semaine prochaine pour examiner le problème plus en détails.
Merci @Yoshi939  pour workaround

**Comment by phik1969** [comment]
bonjour,
j'ai essayé de mettre mon code d'activation dans la configuration, sans succès.
@Yoshi939 c'est bien au niveau de la config du plugin  qui fait le renseigner ?
merci

**Comment by phik1969** [comment]
bonjour,
je confirme, pour moi aussi, cela fonctionne en ajoutant le code au niveau de la configuration.

**Comment by the8tre** [comment]
Effectivement la mise à jour 2024.6 a apporté un changement de comportement en ce qui concerne la gestion du code pour un alarm_control_panel. Le changement est documenté ici: https://developers.home-assistant.io/blog/2024/05/22/alarm_control_panel_validation/
Le vais travailler sur un fix.
