### ISSUE TITLE
Alarme marquée désactivée mais toujours active

### ISSUE THREAD

**Issue by miniboss974** [the8tre/somfy-protexial#59]
Bonjour, je rencontre un problème aléatoire avec Home assistant et l'intégration pour alarme Somfy Protexiom. J'ai souvent une alerte de changement d'état de l'alarme en désactivée alors qu'après vérification par module GSM elle est bien activée. 

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

![1000001955](https://github.com/user-attachments/assets/1afc377a-17a2-49aa-9722-ca76cd40f526)
![1000001957](https://github.com/user-attachments/assets/17dc75a2-39a5-4450-9f28-fd1c92cdad18)

## Debug log

```text

Add your logs here.

```

**Comment by the8tre** [comment]
Difficile de voir d'où pourrait venir le problème.
Est-ce que tu vois dans l'historique des états ces changements ?

**Comment by miniboss974** [comment]
Merci de votre implication.
Je joins des captures d'écran de la remontée d'information "unknow" de l'alarme dans home assistant. Je ne pense pas être prévenu en cas de déclenchement. Je testerai.
Merci

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miniboss974** [comment]
![Screenshot_20241108-075600](https://github.com/user-attachments/assets/725092a8-4136-4494-a685-e39f0caf8109)
![Screenshot_20241108-075637](https://github.com/user-attachments/assets/30af5e29-a896-49ee-91ad-8ed0c7be9963)
![Screenshot_20241108-075759](https://github.com/user-attachments/assets/4370a176-08de-4202-b23e-abb626916d0d)

**Comment by the8tre** [comment]
Est-ce que tu as mis à jour HA en version 2024.11 ?
Si oui le problème de statut d'alarme 'inconnu' devrait être fixé par la release 1.2.2 de l'intégration.
