### ISSUE TITLE
Etat GSM "ko" alors que tout est opérationnel

### ISSUE THREAD

**Issue by lavaredo** [the8tre/somfy-protexial#60]
Merci pour ce module bien fait et bien pratique.

2 problèmes constatés avec une Protexiom de 2020 : 
- L'état du module GSM est renvoyé comme "ko" en permanence alors que tout va bien et que la communication SMS est opérationnelle.
- L'état des autres entités varie parfois sans raison (alarme désactivée, connexion radio ko, etc..) pendant quelques secondes à quelques minutes, alors qu'au niveau de l'alarme rien ne change (cf. autre ticket ouvert il y a 2 semaines). Ceci déclenche nos automatismes home assistant, et rend la situation peu fiable et stressante.

Il n'y a aucun retour concernant l'intégration dans les logs de HA.

Merci pour votre travail ! 👍

**Comment by Pr20100** [comment]
Bonjour, j'ai moi aussi ce soucis et cela semble dépendre notamment du firmware de l'alarme ou du modèle exact.
Pour ma part, je gère 2 installations : 
- Somfy protexiom firmware V9_5 = l'ensemble des capteurs remonte correctement (version avec sirène intérieure séparée)
- Somfy protexiom firmware V10_14 =  le capteur gsm est tout le temps KO (version avec sirène intégrée à la centrale)

J'ai aussi effectivement l'alarme qui affiche un état inconnu de temps à autre, il semble que la remontée d'info ne se fait pas correctement entre l'alarme et le réseau : sur mon switch je constate systématiquement de la perte de paquets et ce uniquement sur l'alarme et c'est ce qui cause cet état "inconnu". La solution est de rester sur un temps de mise à jour pas trop bas : pour moi 30s c'est le mini, 60s c'est bien aussi car plus ce temps est faible plus le nombre de requêtes échouées sera important. De toute façon, dès qu'une commande d'activation ou de désactivation est reçue, l'alarme renvoie automatiquement son état à HA sans délai et met à jour les entités.

Concernant les automatisations il faut simplement s'adapter et le prendre en compte en utilisant des déclencheurs ou conditions adaptés (ex : déclencheur= ouverture porte du garage demandée / conditions= si Alarme_on OU si Alarme_inconnu / alors= désactive Alarme)

J'en profite pour remercier et féliciter le dev pour son travail, c'est vraiment confort de pouvoir utiliser ce système avec HA. Cette alarme est super fiable (tant que le module ip fonctionne...) mais la partie logiciel est à la ramasse depuis un sacré bout de temps côté SOMFY...

**Comment by the8tre** [comment]
Sur mon installation le module GSM est effectivement KO, mais cela est dû au fait que la batterie du-dit module est morte.
Elle était gonflée, j'ai donc abandonné l'idée d'utiliser le module GSM.
![image](https://github.com/user-attachments/assets/41e1dc1c-5d9f-4b6c-8faa-fbd2158c0bb6)

**Comment by lavaredo** [comment]
Bonjour,

merci pour ces retours.
J'ai effectivement une protexiom V10_15.
Toutefois, après de nouveaux tests, il s'avère que l'alarme ne remonte pas du tout les changements d'état immédiatement à HA, mais que l'intégration ne les reçoit que lors des mises à jour.
Cela nécessite donc pour moi de garder un délai de mise à jour bas, et génère donc de nombreuses erreurs dans les états des entités. Il faudra faire avec pour le moment j'imagine, mais je tenais tout de même à remonter les infos.
Et toujours avec mes remerciements et encouragements pour le développeur, qui a mis tout cela bénévolement à notre disposition.

________________________________
De : Pr20100 ***@***.***>
Envoyé : jeudi 7 novembre 2024 10:59
À : the8tre/somfy-protexial ***@***.***>
Cc : lavaredo ***@***.***>; Author ***@***.***>
Objet : Re: [the8tre/somfy-protexial] Etat GSM "ko" alors que tout est opérationnel (Issue #60)


Bonjour, j'ai moi aussi ce soucis et cela semble dépendre notamment du firmware de l'alarme ou du modèle exact.
Pour ma part, je gère 2 installations :

  *   Somfy protexiom firmware V9_5 = l'ensemble des capteurs remonte correctement (version avec sirène intérieure séparée)
  *   Somfy protexiom firmware V10_14 = le capteur gsm est tout le temps KO (version avec sirène intégrée à la centrale)

J'ai aussi effectivement l'alarme qui affiche un état inconnu de temps à autre, il semble que la remontée d'info ne se fait pas correctement entre l'alarme et le réseau : sur mon switch je constate systématiquement de la perte de paquets et ce uniquement sur l'alarme et c'est ce qui cause cet état "inconnu". La solution est de rester sur un temps de mise à jour pas trop bas : pour moi 30s c'est le mini, 60s c'est bien aussi car plus ce temps est faible plus le nombre de requêtes échouées sera important. De toute façon, dès qu'une commande d'activation ou de désactivation est reçue, l'alarme renvoie automatiquement son état à HA sans délai et met à jour les entités.

Concernant les automatisations il faut simplement s'adapter et le prendre en compte en utilisant des déclencheurs ou conditions adaptés (ex : déclencheur= ouverture porte du garage demandée / conditions= si Alarme_on OU si Alarme_inconnu / alors= désactive Alarme)

J'en profite pour remercier et féliciter le dev pour son travail, c'est vraiment confort de pouvoir utiliser ce système avec HA. Cette alarme est super fiable (tant que le module ip fonctionne...) mais la partie logiciel est à la ramasse depuis un sacré bout de temps côté SOMFY...

**Comment by the8tre** [comment]
Effectivement il est difficile de se baser sur les changements d'états vu que quoi qu'il arrive la latence d'interrogation du serveur rentre en jeu.

**Comment by lavaredo** [comment]
Et donc toujours le problème du module GSM "ko" qui est toujours d'actualité, contrairement à ce que la fermeture du ticket laisserait supposer.
________________________________
De : the8tre ***@***.***>
Envoyé : samedi 9 novembre 2024 17:31
À : the8tre/somfy-protexial ***@***.***>
Cc : lavaredo ***@***.***>; Author ***@***.***>
Objet : Re: [the8tre/somfy-protexial] Etat GSM "ko" alors que tout est opérationnel (Issue #60)


Effectivement il est difficile de se baser sur les changements d'états vu que quoi qu'il arrive la latence d'interrogation du serveur rentre en jeu.

**Comment by the8tre** [comment]
Tout les statuts remontés par l'intégration sont directement issus des réponses de la centrale avec un delta correspondant à la période d'interrogation choisie.
Je ne vois pas ce que je peux faire pour régler ces problèmes de fluctuation de statut.
Le commentaire de @Pr20100 est peut-être une piste intéressante pour "absorber" les instabilités au niveau des automatisations elles-même: https://github.com/the8tre/somfy-protexial/issues/60#issuecomment-2461799101

**Comment by lavaredo** [comment]
Oui j'ai bien pris note de ses réponses très pertinentes que je suis en train d'appliquer dans mes automatismes.
Ne reste plus que l'état du module GSM qui renvoie un "ko" inexact (et constant), même si cela peut être vu comme secondaire.
________________________________
De : the8tre ***@***.***>
Envoyé : samedi 9 novembre 2024 18:52
À : the8tre/somfy-protexial ***@***.***>
Cc : lavaredo ***@***.***>; Author ***@***.***>
Objet : Re: [the8tre/somfy-protexial] Etat GSM "ko" alors que tout est opérationnel (Issue #60)


Tout les statuts remontés par l'intégration sont directement issus des réponses de la centrale avec un delta correspondant à la période d'interrogation choisie.
Je ne vois pas ce que je peux faire pour régler ces problèmes de fluctuation de statut.
Le commentaire de @Pr20100<https://github.com/Pr20100> est peut-être une piste intéressante pour "absorber" les instabilités au niveau des automatisations elles-même: #60 (comment)<https://github.com/the8tre/somfy-protexial/issues/60#issuecomment-2461799101>

**Comment by lavaredo** [comment]
Re-bonsoir,

par ailleurs, sur ma protexiom V10_15, et après de nombreux tests minutieux aujourd'hui que je viens de terminer, il s'avère que la détection de mouvement n'est pas remontée correctement non plus, ce qui rend du coup l'intégration inutile dans mon cas de figure.
Il me semble donc que la remontée correcte de ces 2 entités (mouvement et GSM) sur certaines Protexiom sont un bug important qui nécessiteraient l'ouverture d'un ticket. Mais comme je suis novice sur Github, je vous laisse gérer ça. Et je vous remercie toujours pour votre travail.


________________________________
De : the8tre ***@***.***>
Envoyé : samedi 9 novembre 2024 18:52
À : the8tre/somfy-protexial ***@***.***>
Cc : lavaredo ***@***.***>; Author ***@***.***>
Objet : Re: [the8tre/somfy-protexial] Etat GSM "ko" alors que tout est opérationnel (Issue #60)


Tout les statuts remontés par l'intégration sont directement issus des réponses de la centrale avec un delta correspondant à la période d'interrogation choisie.
Je ne vois pas ce que je peux faire pour régler ces problèmes de fluctuation de statut.
Le commentaire de @Pr20100<https://github.com/Pr20100> est peut-être une piste intéressante pour "absorber" les instabilités au niveau des automatisations elles-même: #60 (comment)<https://github.com/the8tre/somfy-protexial/issues/60#issuecomment-2461799101>

**Comment by Pr20100** [comment]
> Sur mon installation le module GSM est effectivement KO, mais cela est dû au fait que la batterie du-dit module est morte.
> 
> Elle était gonflée, j'ai donc abandonné l'idée d'utiliser le module GSM.
> 
> ![image](https://github.com/user-attachments/assets/41e1dc1c-5d9f-4b6c-8faa-fbd2158c0bb6)
> 
> 

Si cela t'intéresse, j'en ai encore une neuve qui traîne (par neuve j'entends jamais utilisée et pas gonflée). Je peux facilement te l'expédier.
![image](https://github.com/user-attachments/assets/08c4b4a3-2053-4e4b-b160-0f1add5b916d)

**Comment by the8tre** [comment]
@Pr20100 oui ça m'intéresse si tu n'en fais rien.
Peux-tu me contacter sur mon mail the.8tre@gmail.com ?
Merci !
