### ISSUE TITLE
Core_update 2024.11.0 = statut "inconnu" permanent

### ISSUE THREAD

**Issue by Pr20100** [the8tre/somfy-protexial#61]
Salut!

J'ai testé hier soir l'installation sur un conteneur séparé de la nouvelle version du Core en 2024.11.0 : 

- L'état de l'entité alarm_control_panel.'monalarme' remonte "inconnu" en permanence
- Les capteurs remontent tous correctement
- L'activation et la désactivation du système fonctionnent toujours

Après une recherche rapide il apparait que la dénomination des états pour AlarmControlPanelEntity vont changer, je te met le lien ci-dessous  : 

[https://developers.home-assistant.io/blog/2024/10/22/new-alarm-state-property/](url)

> As of Home Assistant Core 2024.11, we have introduced the alarm_state property in the AlarmControlPanelEntity. This newly added property should be used instead of directly setting the state property.

> The new alarm_state property should return its state using the new AlarmControlPanelState enum instead of as previously, setting the state using the STATE_ALARM_* constants.

> There` is a one-year deprecation period, and the constants will stop working from 2025.11 to ensure all custom integration authors have time to adjust.

Par contre vu cette dernière phrase, je ne comprend pas pourquoi cela pose problème déjà maintenant, il se pourrait qu'une erreur se soit glissée dans cette update...

Bonne journée!

**Comment by the8tre** [comment]
Merci pour l'info, je vais prendre en compte ce changement avant l'année prochaine :)
Je suis toujours en 2024.10.4, je testerai la 2024.11.0 quand j'aurai un moment.
C'est effectivement bizarre qu'un dépréciation à venir pose problème.

**Comment by Pr20100** [comment]
Ils ont encore fait beaucoup de modifs et de gros ajouts ce mois-ci, d'autres intégrations et services m'ont aussi remontés des erreurs.

**Comment by the8tre** [comment]
Ca vaut peut-être ce coup d'attendre une future 2024.11.X qui pourrait contenir des fixes

**Comment by agira334** [comment]
Même probleme ici, je confirme.

**Comment by gomes94s** [comment]
Je confirme, j'ai restauré la version précédente de HA et ça refonctionne.

**Comment by danwador** [comment]
Idem Je confirme

**Comment by the8tre** [comment]
Un fix est en cours de préparation.

**Comment by the8tre** [comment]
@danwador, @Pr20100, @agira334, @gomes94s j'ai livré une version 1.2.2
Dîtes-moi si je problème est résolu pour vous avant que je puisse fermer ce bug.

**Comment by gomes94s** [comment]
Je fais la mis à jour de HA et je teste

**Comment by gomes94s** [comment]
Super ça fonctionne pour moi. Merci 👍

**Comment by Pr20100** [comment]
Merci pour le fix! Je teste ça ce soir, et comme on dit, "si pas de nouvelles, bonne nouvelle". Bonne soirée

**Comment by agira334** [comment]
Ça marche nickel. Merci !

**Comment by danwador** [comment]
Merci parfait !
