### ISSUE TITLE
Etat GSM et état Détection mouvement ne remontent pas correctement sur Protexiom V10_15 de 2020.

### ISSUE THREAD

**Issue by lavaredo** [the8tre/somfy-protexial#63]
Bonjour,

j'ouvre un ticket séparé pour plus de clarté, désolé si ce n'est pas dans les usages, dans ce cas fermez-le.
Merci au développeur pour ce travail.

Après des tests extensifs, l'état GSM et l'état de la détection de mouvement ne remontent pas sur une protexiom V10_15 de 2020.

le GSM reste "ko" alors qu'il est opérationnel (et remonte OK dans l'interface de l'alarme), et la détection mouvement reste en "non détecté" même lorsqu'une alarme par mouvement est déclenché (et que HA s'est bien mis à jour avec la centrale après le déclenchement de l'alarme).

Merci.

**Comment by the8tre** [comment]
Vérifie manuellement le retour de `http://192.168.1.234/status.xml` (en adaptant l’URL à ton installation). 
Est ce que le statut GSM correspond à ce que tu vois dans l’interface Somfy et dans HA ?
Active le debug sur l’intégration et partage les logs.

**Comment by lavaredo** [comment]
Bonjour, voici les infos demandées (et même plus, puisque j'ai tenu aussi à envoyer les logs concernant le défaut de détection de mouvement, pas seulement le GSM qui est moins important) : 

ALARME DESACTIVEE, RETOUR GSM INCORRECT : 

![Tout ok](https://github.com/user-attachments/assets/d2b77784-e196-4e41-af51-cc3a98d1adc9)

![tout ok 1](https://github.com/user-attachments/assets/3fbeab28-688b-4183-9c1f-68a4228bf799)


ALARME ACTIVEE PAR DETECTION DE MOUVEMENT : 

![intrusion](https://github.com/user-attachments/assets/45396399-e74a-41d6-8c9e-3a71a54e67b2)

![intrusion 1](https://github.com/user-attachments/assets/ea701912-4a96-4307-bed9-43265957b548)


Je n'ai inclus aucun log de HA car absolument rien n'y apparait au sujet de l'intégration.
Merci.

**Comment by the8tre** [comment]
Pour ce qui est de la détection de mouvement j'ai l'impression que la désynchro est dûe au `nok_lint` que je n'ai jamais vu sur ma centrale. Je peux fixer ça facilement.

Par contre pour le GSM je n'ai toujours pas vraiment de piste.
Les traces debug devraient peut-être pouvoir m'aider.
Active l'enregistrement pendant quelques minutes, et ensuite lorsque tu vas le désactiver le fichier de traces devraient se télécharger.
![image](https://github.com/user-attachments/assets/cb537b06-98d1-49b2-9896-97fed78ef3a6)

**Comment by lavaredo** [comment]
- Attention c'est "nok_int"  le message de détection de mouvement, tu l'as mal recopié, au cas où tu voudrais l'intégrer.

- Je vais peut-être dire une bêtise, mais pour la détection de mouvement, pour simplifier, tu ne peux pas afficher une détection tout simplement si la centrale renvoie n'importe quoi d'autre que "ok" ? Si j'ai bien compris, SOMFY a eu l'intelligence de ne pas garder les mêmes messages de notification sur les différentes versions, ça permettrait de contourner le problème. C'est valable également pour les autres entités : il se pourrait que d'autres entités ne fonctionnent pas également à cause de ça, comme la radio ou les boitiers, je ne peux pas tester ça.

- Pour le GSM, ça ne serait pas un problème d'accent ? (Regarde les logs !) Ou une coquille dans le recopiage du message de la centrale, justement ? "GSM connecté au réseau" (copie exacte). Là aussi, vu la quantité d'autres messages existants que j'ai vu défiler (initialisation, module GSM arrêté, non connecté, erreur, etc...), il serait bon d'afficher une erreur dès que le message correct n'est pas renvoyé par la centrale, qu'en penses-tu ?

- Voici le fichier demandé : 
[home-assistant_somfy_protexial_2024-11-10T23-35-24.537Z.log](https://github.com/user-attachments/files/17693527/home-assistant_somfy_protexial_2024-11-10T23-35-24.537Z.log)

**Comment by lavaredo** [comment]
Bonsoir, merci pour ton travail et ta réactivité.
L'état GSM remonte bien comme "ok" maintenant. Toutefois, n'étant plus sur place depuis ce soir et pour un petit bout de temps, c'est tout ce que je peux te dire, je ne peux pas tester pour le moment : 
- Ni la détection de mouvement
- Ni le basculement correct des autres entités en ko

Pendant que l'on y est, voici 2 suggestions d'amélioration pour la nouvelle version :
- Est-ce que tu ne pourrais pas mettre le mot "somfy" ou "protexiom" dans le nom de toutes les entités de l'intégration, afin qu'on puisse les retrouver facilement dans la liste complète des entités ? (Comme dans de nombreuses autres intégrations, comme RTE, ENEDIS, etc...)
- Quand on crée une automatisation, la liste des états sélectionnable ne correspond pas aux états affichés dans le tableau de bord, ce n'est pas très clair. Exemple : le GSM est affiché comme "ok" ou "ko", mais dans les automatisations on doit choisir entre "activé" ou "désactivé". Je suppose que "ok" correspond à "activé" mais c'est ambigu et c'est un risque d'erreur. Merci ! :-)

**Comment by the8tre** [comment]
Merci pour ton retour.
Je vais fermer cette issue, vu que le problème initial semble réglé.

Je prends note de tes remarques sur le nommage et le statut des éléments. J'ai un chantier en cours pour exposer individuellement les éléments rattachés à la centrale.
