### ISSUE TITLE
Toutes les entités renvoient des états faux, simultanément et à intervalles réguliers, pdt plusieurs minutes.

### ISSUE THREAD

**Issue by lavaredo** [the8tre/somfy-protexial#67]
Protexiom V10_15 de 2020
Version  1.3.0-rc5

A intervalles réguliers, simultanément, et pendant plusieurs minutes, tous les états indiquent l'inverse de la vérité ("ko", "piles faibles", "mvt détécté", "Alarme desactivée", etc.) sans raison objective (aucun évènement réel).
Il serait logique d'avoir un état "indisponible" en cas de défaut de communication avec l'alarme, mais pas un message de détection d'erreur, ce qui rend toute automatisation impossible, puisqu'elle serait déclenchée sans raison en permanence.
Le log vient demain, après une nuit d'enregistrement pour retrouver l'erreur.
Merci.

![Screenshot 2024-11-18 at 17-55-39 Aperçu – Home Assistant](https://github.com/user-attachments/assets/daf3e3c2-3dcb-4ce3-9969-c5e02304e9a4)
![Screenshot 2024-11-18 at 17-56-02 Aperçu – Home Assistant](https://github.com/user-attachments/assets/151e941d-a36a-473c-bef9-502ab6f1fcb1)
![Screenshot 2024-11-18 at 17-56-20 Aperçu – Home Assistant](https://github.com/user-attachments/assets/94d93125-c099-4e2d-a86d-a5eabd8c1b09)
![Screenshot 2024-11-18 at 17-56-36 Aperçu – Home Assistant](https://github.com/user-attachments/assets/de8f21d2-b566-4824-8466-127849de9cd5)
![Screenshot 2024-11-18 at 17-57-06 Aperçu – Home Assistant](https://github.com/user-attachments/assets/5d59bb26-1788-4e6f-812f-128ae974932f)
![Screenshot 2024-11-18 at 17-57-22 Aperçu – Home Assistant](https://github.com/user-attachments/assets/627b9ebd-c27e-4f1e-90e3-1d238dd957ed)
![Screenshot 2024-11-18 at 17-57-37 Aperçu – Home Assistant](https://github.com/user-attachments/assets/a9bfca3d-df7e-4591-9ea6-c419d029bf2d)

**Comment by the8tre** [comment]
Merci pour ton retour.
Par contre je te déconseille d’installer les versions release candidate ou bêta qui peuvent certainement avoir des bugs. 
Par exemple les versions 1.3.0-rc* sont destinées à la mise au point du support d’un nouveau modèle de centrale.

**Comment by lavaredo** [comment]
Voici le fichier log. Il y a une occurrence du problème à 5h du matin. Je te confirme que le problème était déjà présent avec la version 1.2.3
Merci

[home-assistant_somfy_protexial_2024-11-30T11-47-51.901Z.log](https://github.com/user-attachments/files/17966392/home-assistant_somfy_protexial_2024-11-30T11-47-51.901Z.log)

![Screenshot 2024-11-30 at 19-34-31 Aperçu – Home Assistant](https://github.com/user-attachments/assets/1ae5ee69-a231-4048-ab31-1306db8cd2e0)

**Comment by lavaredo** [comment]
L'erreur semble simple à résoudre : parfois la centrale déconne, et renvoie "none" comme état de tous les éléments (voir extrait du log ci-dessous). Il suffit donc de faire en sorte que ton intégration renvoie "indisponible" dans ces cas-là, plutôt qu'un état désactivé. Encore mieux : faire en sorte que ton intégration ne renvoie rien, et attende la mise à jour suivante !

2024-11-30 05:00:40.143 DEBUG (MainThread) [custom_components.somfy_protexial] zoneA:None, zoneB:None, zoneC:None, battery:None, radio:None, door:None, alarm:None, box:None, gsm:None, recgsm:None, opegsm:None, camera:None
2024-11-30 05:00:40.143 DEBUG (MainThread) [custom_components.somfy_protexial] Finished fetching Somfy Protexial status update data in 0.052 seconds (success: True)

**Comment by the8tre** [comment]
Je dois reconnaitre que la gestion des états est un peu boiteuse :-)
J'essaye de rendre ça un peu plus carré en ajoutant la notion d'indisponibilité et, peut-être, la prise en charge d'un nombre d'essais échoués avant de réagir.

Quelques questions subsidiaires:
- Quelle fréquence de rafraîchissement as-tu défini ?
- Je vois dans tes logs des `Command failed: Unknown errorCode: (0x0802)`
  Est-ce que tu peux mettre installer la version `1.2.4` de l'intégration qui dump la page d'erreur en cas de code inconnu.
  Ca permettra peut-être d'avoir plus d'info sur cette mystérieuse erreur.

**Comment by the8tre** [comment]
Tu peux installer la `1.2.5-rc1` pour voir si le comportement est plus stable.

**Comment by lavaredo** [comment]
Hello, j'ai installé la version 1.2.5-rc1 et j'ai laissé tourner toute la journée. Il n'y a plus d'état "faux" reportés, simplement un état "indisponible" qui peut durer de quelques secondes à plusieurs minutes, simultanément sur toutes les entités. C'est mieux, et si à l'avenir on peut éviter ces indisponibilités, comme tu l'avais suggéré, ça sera parfait niveau sécurité, pour éviter tout downtime. On parle quand même d'un élément de sécurité critique (la mienne fait aussi ma sécurité incendie, en plus).

Pour répondre à ta question, ma fréquence de rafraichissement est actuellement de 30 sec, Plus ne serait pas acceptable pour moi niveau sécurité. 15s. serait même encore mieux, quand tout marchera bien.

Par ailleurs, quand j'y retournerai, je vérifierai le bon fonctionnement de l'intégration en cas de déclenchement de l'alarme, ce que je n'ai pas encore testé, étant donné les problèmes rencontrés jusqu'ici. On se reparlera possiblement à ce moment là :-)

Voici les logs et le screenshot correspondant. Merci pour ton travail.

[home-assistant_somfy_protexial_2024-12-02T15-27-59.671Z.log](https://github.com/user-attachments/files/17980513/home-assistant_somfy_protexial_2024-12-02T15-27-59.671Z.log)

![Screenshot 2024-12-02 at 16-26-27 Journal – Home Assistant](https://github.com/user-attachments/assets/269a0fa2-3a63-4765-a104-0e42a0262ca9)

**Comment by the8tre** [comment]
J'ai déjà inclus dans cette version un mécanisme de retry (jusqu'à 3 fois) lorsque les requêtes vers la centrale partent en timeout.
Il semblerait qu'il ne se soit déclenché qu'une seule fois à `07:57:13`
```js
2024-12-02 07:57:13.859 ERROR (MainThread) [custom_components.somfy_protexial] Retryable error raised Timeout error fetching information from http://192.168.1.181/status.xml
2024-12-02 07:57:13.867 ERROR (MainThread) [custom_components.somfy_protexial] Will retry and return last known data
```
Les phases d'indisponibilité ne sont donc pas dues à des problème de connexion.
En regardant les logs je vois que la centrale ne renvoie pas toujours une valeur pour les différents éléments.
Comme par exemple cet appel à `05:26:45` où aucun champ n'a de valeur:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
  <zone0></zone0>
  <zone1></zone1>
  <zone2></zone2>
  <defaut0></defaut0>
  <defaut1></defaut1>
  <defaut2></defaut2>
  <defaut3></defaut3>
  <defaut4></defaut4>
  <gsm></gsm>
  <recgsm></recgsm>
  <opegsm></opegsm>
  <camera></camera>
</response>
```
Et la situation semble persister jusqu'au login suivant lorsque la session courante a expiré, et cela correspond exactement à ce qu'on voit dans ton screenshot.

Je peux peut-être détecter ce genre phénomène et forcer un login pour tenter de rétablir les choses.

**Comment by lavaredo** [comment]
Magnifique, bien vu. Je reste à ta disposition pour les tests.

**Comment by lavaredo** [comment]
7 min d'indisponibilité aujourd'hui, c'est conséquent. Je suis vraiment curieux de savoir ce qui crée ça quand tu auras trouvé.

![Screenshot 2024-12-03 at 19-05-55 Aperçu – Home Assistant](https://github.com/user-attachments/assets/252a88e8-adfb-489a-9ed6-646ba5302537)

**Comment by lavaredo** [comment]
7 min d'indisponibilité aujourd'hui, c'est conséquent. Je suis vraiment curieux de savoir ce qui crée ça quand tu auras trouvé.

![Screenshot 2024-12-03 at 19-05-55 Aperçu – Home Assistant](https://github.com/user-attachments/assets/252a88e8-adfb-489a-9ed6-646ba5302537)

**Comment by the8tre** [comment]
Si tu as les logs sur la même période que tes screenshots je suis preneur

**Comment by lavaredo** [comment]
Je n'ai pas le log du screenshot précédent, mais voici de nouvelles périodes d'indisponibilité longues, avec le log correspondant.

[home-assistant_somfy_protexial_2024-12-04T17-40-18.608Z.log](https://github.com/user-attachments/files/18012177/home-assistant_somfy_protexial_2024-12-04T17-40-18.608Z.log)

![Screenshot 2024-12-04 at 18-40-54 Journal – Home Assistant](https://github.com/user-attachments/assets/9ffd0f05-635d-4129-8db9-3c0ee46e7f41)

**Comment by the8tre** [comment]
La version `1.2.5-rc2` détecte lorsque la centrale a un coup de mou sur les statuts et re-login + re-essaie
🤞

**Comment by lavaredo** [comment]
Magnifique merci, ça c'est du développement dynamique ! :-)
C'est parti pour 24h d'essais.

**Comment by lavaredo** [comment]
Bon, cela a l'air beaucoup plus stable, pas de déconnexion reportée en 24h, voici un log (court) de quand tout semble bien aller, pour voir si tu détectes d'autres anomalies sous-jacentes, ou si tu peux fermer le ticket.

[Log ok.log](https://github.com/user-attachments/files/18049559/Log.ok.log)

J'ai donc enfin pu pousser les tests plus loin, notamment dans les scénarios de déclenchement de l'alarme, et de déclenchement des automatisations. Là pour le moment il y a encore du travail, hélas (Voir mon autre ticket).

**Comment by the8tre** [comment]
Fixé depuis la version `1.2.5-rc2`
